---
pages:
- blog/some-info.md
hide_body: false
fields:
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: false
- name: comments
  label: Comments
  type: boolean
  hidden: false
  default: false
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: showpagemeta
  label: Showpagemeta
  type: boolean
  hidden: false
  default: true
- name: showcomments
  label: Showcomments
  type: boolean
  hidden: false
  default: true
